package com.aat

import com.android.build.gradle.api.ApplicationVariant
import groovy.json.JsonSlurper
import org.gradle.api.DefaultTask
import org.gradle.api.tasks.TaskAction

class DownloadTextTask extends DefaultTask {

    ApplicationVariant applicationVariant
    String variantName
    TextPluginExtension textPlugin
    def ws

    DownloadTextTask() {
        super()
    }

    @TaskAction
    def load() throws IOException {
        textPlugin = project.texts
        if (textPlugin.ws) {
            initWsUrl();
            ws = new URL(textPlugin.ws)
            textPlugin.languages.add(textPlugin.defaultLanguage)
            textPlugin.languages.each {
                loadTextWithLang(it.toLowerCase())
            }
        }
    }

    private void loadTextWithLang(String lang) {
        def json = new JsonSlurper().parseText(ws.getText(
            requestProperties: [Accept: 'application/json', language: lang, translateKey: '%_$s']
        ))
        def dir = "values";
        if (!lang.equals(textPlugin.defaultLanguage)) {
            dir = "values-" + lang
        }
        String currentDir = new File(".").getAbsoluteFile().getParent()
        currentDir = currentDir + '/app/src/main/res/'

        File myDir = new File(currentDir + dir);
        if (!myDir.exists()) {
            myDir.mkdirs();
        }
        File file = new File(myDir.getAbsolutePath() + File.separator + "strings.xml")
        file.write "<?xml version=\"1.0\" encoding=\"utf-8\"?>\n"
        file << "<!-- DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED BY groovy script made by aat -->\n"
        file << "<resources>\n"
        json.data.texts.each { myText ->
            if (myText.id != null && myText.value != null) {
                if (myText.value.contains("&")) {
                    myText.value = myText.value.replaceAll("&", "&amp;")
                } else if (myText.value.contains("'")) {
                    myText.value = myText.value.replaceAll("'", "\\\\'")
                }
                file << "    <string name=\"${myText.key.trim()}\">$myText.value</string>\n"
                // println myText.key + ' ' + myText.value
            }
        }

        // Theses keys will be addded by customer later
        if (lang == textPlugin.defaultLanguage && textPlugin.missingKeys != null) {
            file << "    <!-- Keys added by user -->"
            file << textPlugin.missingKeys
        }
        file << "</resources>"
        println "We've done with [" + lang + "]"
    }

    private void initWsUrl() {
        ws = text.ws
        if (text.variantToWs) {
            if (text.variantToWs[variantName]) {
                ws = text.variantToWs[variantName]
            }
        }
    }
}

